"""Updated credits management in user model.

Revision ID: 125b328c664e
Revises: cd504b8a7b39
Create Date: 2026-05-17 11:19:23.096994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125b328c664e'
down_revision = 'cd504b8a7b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('left_credits', sa.Integer(), nullable=True))
        batch_op.drop_column('credits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.INTEGER(), nullable=True))
        batch_op.drop_column('left_credits')
        batch_op.drop_column('total_credits')

    # ### end Alembic commands ###
