"""Updated datatype of last_generation column in user model.

Revision ID: 3041e233a42b
Revises: 02dd3d10e533
Create Date: 2026-05-28 21:00:08.684736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3041e233a42b'
down_revision = '02dd3d10e533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_generation',
               existing_type=sa.TIME(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_generation',
               existing_type=sa.Float(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
