"""Added user_list column to promo_code table.

Revision ID: 32d89e144e9b
Revises: 
Create Date: 2026-06-15 11:18:18.626272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d89e144e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_list', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.drop_column('user_list')

    # ### end Alembic commands ###
