"""Added 'last_reset_month' column in user model.

Revision ID: 5d95d3a63779
Revises: 125b328c664e
Create Date: 2026-05-17 12:12:22.947330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d95d3a63779'
down_revision = '125b328c664e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_reset_month')

    # ### end Alembic commands ###
