"""Added deleted column in captions and headlines model.

Revision ID: 942ce036ed42
Revises: b5ea66d1ae68
Create Date: 2026-05-14 20:07:58.107446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942ce036ed42'
down_revision = 'b5ea66d1ae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('headline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('headline', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('caption', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
