"""Added ai_tone and ai_creativity column to user table.

Revision ID: a955ac363c29
Revises: 
Create Date: 2026-05-14 12:39:19.102517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a955ac363c29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_tone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_creativity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_creativity')
        batch_op.drop_column('ai_tone')

    # ### end Alembic commands ###
