"""Added ai_lang column to user table.

Revision ID: b5ea66d1ae68
Revises: a955ac363c29
Create Date: 2026-05-14 12:48:46.576483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ea66d1ae68'
down_revision = 'a955ac363c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_lang', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_lang')

    # ### end Alembic commands ###
