"""Added pyament method column to payment model.

Revision ID: fd5a8ee5e9b7
Revises: 3041e233a42b
Create Date: 2026-05-29 15:03:37.437351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5a8ee5e9b7'
down_revision = '3041e233a42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
